### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by octotree** [gkdr/carbons#10]
Did I miss something or is there no LICENSE file? As this work is closely related to your 'lurch' work, I would assume it is also GPL-v3, but I would be really happy if you could add a license.

Thanks :-)

**Comment by octotree** [comment]
That was quick. Thanks :+1:

**Comment by gkdr** [comment]
Not a problem :D That is one of the easier things to fix.
I made it GPLv2+ to match libpurple. My other projects had to be GPLv3 because libsignal is too.
