### ISSUE TITLE
Newest version not loaded on Windows

### ISSUE THREAD

**Issue by pannal** [gkdr/carbons#18]
I'm on Pidgin Windows 2.12.0 - after upgrading to the newest carbons.dll from the binary source, carbons doesn't show up in Plugins anymore and `/carbons` is an unknown command.

**Comment by EionRobb** [comment]
That'll be my fault from issue #17 
Can you get a debug log of the plugins list:
* From the buddy list, Help->Debug Window
* Leave the debug window open and open Tools->Plugins
* Close the plugins window
* Copy-paste the output of the debug log here

**Comment by RayZopf** [comment]
`\AppData\Roaming\.purple\plugins\carbons.dll is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?`

**Comment by pannal** [comment]
Yep, exactly that @RayZopf

**Comment by EionRobb** [comment]
I've made an updated build with `-DPURPLE_PLUGINS` at https://eion.robbmob.com/carbons.dll

**Comment by pannal** [comment]
I'm receiving a ton of those: `(22:31:20) jabber: XML parser error for JabberStream 080429D0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute` - not sure whether it's lurch or carbons or neither.

Both load now again, anyways.

**Comment by gkdr** [comment]
Sorry @pannal, I didn't see your edits because they don't cause email notifications.
This should work independently of lurch/OMEMO/whatever, so if you want to confirm this plugin works, you can just try it on a regular conversation (that is not end-to-end encrypted).

**Comment by RayZopf** [comment]
exchanging messages between my own Pidgin - Gajim (prio 0) works.
But with carbons plugin enabled I get in Pidgin the message sent from Gajim and additionally
```
(09:38:31) 
There was an error decrypting an OMEMO message addressed to this device. See the debug log for details.
```

**Comment by gkdr** [comment]
Since this applied to an older version, I'm going to close the issue. Please open a new one if the problem persists.
