### ISSUE TITLE
Not receiving message when multiple devices are used for the same user

### ISSUE THREAD

**Issue by 2Belette** [gkdr/carbons#2]
Working to give you debug logs...

**Comment by 2Belette** [comment]
I have made some other tests and was about to send you logs but it is like you solved the issue....
Have you changed something apart adding the debug branch?
I can now see the message I receive from Pidgin and Conversation and vice versa...

I still have an issue but not the same I have explained on the tittle:  I am not getting my historical (my sent messages) on the other device when I send a message from a device..
For example:
from conversation, I am writting : hey
from Pidgin, I am not seing it
samething vice versa

Message in reception are ok

**Comment by gkdr** [comment]
No, I did not change anything but adding one line of debug output. Maybe you weren't on the newest version before? Glad that part is resolved though.

For the next problem, I still need to see some debug output so I can help you :D The line I added should help here too.

**Comment by 2Belette** [comment]
I tried again for the first issue (in the title) and I realized that I needed to put my friend into blacklist add and then blacklist remove to make it work... after that I can see this message on both Conversation and Pidgin for the moment...
BUT as soon as I go back to Conversation and start chatting again only from Conversation I am not seeing the message from my friend on Pidgin...

Here is the debug on a message received from my friend on Conversation but not on Pidgin (even if obviously something happened in the log):

> Please take a look into your email as I don't know if there is some confidential information in the debug log regarding my OMEMO keys so I preferred to send you by mail :)

For the message I send, here the debug from pidgin when I am sending a message from Conversation.
Obviously Pidgin is receiving information on the same time but it is like the plugin is not able to interpret it correctly, here are the debug : 

> Please take a look into your email as I don't know if there is some confidential information in the debug log regarding my OMEMO keys so I preferred to send you by mail :)

**Comment by gkdr** [comment]
Maybe this new version will help.
By the way, anything crypto-related on the debug log is already encrypted and not confidential at all (as it is supposed to be sent that way), you only have to remove JIDs if you care.

**Comment by 2Belette** [comment]
Hi thanks for your message.
I just tested and it is not better on this version.
I confirm I see the carbbon copy on my conversation when I am writing a message from pidgin but the reverse is not true.
After git pull the latest version it is like the debug version is not producing any more debug is it normal? (I would like to help you finding the issue)

**Comment by gkdr** [comment]
Which version number does the plugin have in Pidgin when you look at the _Tools -> Plugins_ window?

**Comment by 2Belette** [comment]
I got:

XMPP Message Carbons 0.1.3
Implements XEP-0280: Message Carbons

**Comment by gkdr** [comment]
Ah, that's okay then, I didn't only add new debug output but I also changed the wording of the regular messages to be more precise.

>I confirm I see the carbbon copy on my conversation when I am writing a message from pidgin but the reverse is not true.

Just to be clear: The reverse means writing a message from Conversations?

In any case, can you give me the debug log output at the moment when that situation happens? The more precise wording in the new version could help me find out what's happening anyway.
If you want, you can send it via email again.

**Comment by gkdr** [comment]
IIRC we figured this out to be a server issue via email/chat, , so I'm just going to close this.
