### ISSUE TITLE
Unable to see encrypted carbons sent by Conversations, maybe other clients

### ISSUE THREAD

**Issue by sfjes** [gkdr/carbons#20]
I'm unable to see the OMEMO encrypted contents of carbons sent by Conversations IM client. Instead of seeing the expected carbon contents (the message I sent), I see "I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo", with the <encrypted> payload ignored.

This appears to happen when the carbon includes both a <body> with the above contents and encrypted contents, which is something Conversations began doing in recent versions.

**Comment by gkdr** [comment]
Thanks for the report! According to my tests I fixed it, tell me if the issue persists though.
