### ISSUE TITLE
Didn't receive carbons copy of messages that was sent when pidgin was offline

### ISSUE THREAD

**Issue by wladmis** [gkdr/carbons#37]
When both pidgin and some other XMPP client with the same account are online, they both receive messages that are sent to this account. But if pidgin is offline and some other XMPP client is online, and a message is sent to this account, pidgin will not receive the message when it turns online.

**Comment by matslarson** [comment]
This is expected behavior if your server does not support MAM.

The readme clearly states the following:
Caveats
Note that this only synchronizes messages of devices that are online at the same time - for history synchronization, MAM is needed. There is currently no libpurple plugin for this.

**Comment by wladmis** [comment]
> This is expected behavior.
> 
> The readme clearly states the following:
> Caveats
> Note that this only synchronizes messages of devices that are online at the same time - for history synchronization, MAM is needed. There is currently no libpurple plugin for this.

Oh, I missed that. Thank you for pointing!

Related ticket on Pidgin trac: [Support XEP-0313 aka MAM (Message Archive Mgmt)](https://developer.pidgin.im/ticket/15653)

I'm not sure that this issue should be open while it depends on Pidgin or side plugin missing functionality.

**Comment by gkdr** [comment]
Hi! As matslarson already pointed out (thank you!), "offline messages" are not part of the Message Carbons XEP, so there isn't really a way to resolve this. As far as I understood your last reply, you won't mind if I just close this issue. Hope this plugin can still be a bit useful to you!
