### ISSUE TITLE
Need LICENSE

### ISSUE THREAD

**Issue by shtrom** [gkdr/carbons#39]
lurch is GPL3. Is carbons too?

**Comment by shtrom** [comment]
Dupe of #10 and #35, but it would be good to add a LICENSE file so GitHub finds it.

GPL2+ it sit.

**Comment by gkdr** [comment]
Sounds like a good idea. Do you happen to know if a plugin for a GPL2 lib like libpurple also needs to be GPL?

**Comment by EionRobb** [comment]
Since it links to a GPL library, it needs to be a GPL-compatible license http://gplv3.fsf.org/wiki/index.php/Compatible_licenses#GPLv2-compatible_licenses

**Comment by shtrom** [comment]
Isn't lurch GPL3?

**Comment by gkdr** [comment]
Good to know, thanks! Probably can't change the license now since there's other contributors, but Ill try to find out if that's actually true.

**Comment by EionRobb** [comment]
You've already mentioned that you're going for a gpl2+ licence in your headers? That's compatible :)
Just  needs the license file to match

**Comment by Neustradamus** [comment]
Very important.

**Comment by selurvedu** [comment]
@Neustradamus it's already in the dev branch.

**Comment by Neustradamus** [comment]
@gkdr: Thanks :)
