### ISSUE TITLE
Build error, possibly a linking error.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [gkdr/carbons#46]
mkdir -p build
cc -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -std=c11 -Wall -g -Wstrict-overflow -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_DEFAULT_SOURCE -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I./headers/jabber -fPIC -shared -DPURPLE_PLUGINS -c ./src/carbons.c -o build/carbons.o
cc -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -std=c11 -Wall -g -Wstrict-overflow -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_DEFAULT_SOURCE -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I./headers/jabber -fPIC -shared -DPURPLE_PLUGINS ./build/carbons.o -o build/carbons.so  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu -ldl -lm -lglib-2.0 -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -L/usr/lib64/purple-2 -lxml2 -L/usr/lib64 -lz -llzma -lm -ldl -lxmpp -Wl,-rpath,/usr/lib64/purple-2
./build/carbons.o: In function `carbons_enable_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:198: undefined reference to `purple_connection_get_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:198: undefined reference to `purple_account_get_username'
./build/carbons.o: In function `carbons_filter_invalid':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:54: undefined reference to `purple_account_get_username'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:56: undefined reference to `xmlnode_get_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:57: undefined reference to `xmlnode_get_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:57: undefined reference to `purple_debug_warning'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:62: undefined reference to `xmlnode_free'
./build/carbons.o: In function `carbons_discover_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:216: undefined reference to `purple_connection_get_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:216: undefined reference to `purple_account_get_username'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:223: undefined reference to `xmlnode_get_child_with_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:234: undefined reference to `xmlnode_get_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:236: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:238: undefined reference to `jabber_iq_new'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:239: undefined reference to `xmlnode_new_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:240: undefined reference to `xmlnode_set_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:242: undefined reference to `jabber_iq_set_callback'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:243: undefined reference to `jabber_iq_send'
./build/carbons.o: In function `carbons_xml_received_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:89: undefined reference to `xmlnode_get_child_with_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:91: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:93: undefined reference to `purple_connection_get_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:98: undefined reference to `xmlnode_get_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:104: undefined reference to `xmlnode_get_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:142: undefined reference to `xmlnode_copy'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:143: undefined reference to `xmlnode_free'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:116: undefined reference to `xmlnode_get_child_with_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:118: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:120: undefined reference to `purple_connection_get_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:125: undefined reference to `xmlnode_get_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:131: undefined reference to `xmlnode_get_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:138: undefined reference to `xmlnode_new_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:139: undefined reference to `xmlnode_set_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:141: undefined reference to `purple_debug_info'
./build/carbons.o: In function `carbons_xml_stripped_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:166: undefined reference to `xmlnode_get_child_with_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:171: undefined reference to `xmlnode_get_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:176: undefined reference to `xmlnode_get_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:176: undefined reference to `jabber_get_bare_jid'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:177: undefined reference to `purple_connection_get_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:178: undefined reference to `purple_find_conversation_with_account'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:183: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:184: undefined reference to `xmlnode_get_data'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:185: undefined reference to `xmlnode_get_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:185: undefined reference to `purple_conversation_write'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:188: undefined reference to `xmlnode_free'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:189: undefined reference to `xmlnode_free'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:180: undefined reference to `purple_conversation_new'
./build/carbons.o: In function `carbons_account_connect_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:254: undefined reference to `purple_account_get_protocol_id'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:259: undefined reference to `purple_account_remove_setting'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:264: undefined reference to `purple_account_get_connection'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:264: undefined reference to `purple_connection_get_protocol_data'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:265: undefined reference to `jabber_iq_new'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:266: undefined reference to `xmlnode_set_attrib'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:267: undefined reference to `xmlnode_new_child'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:268: undefined reference to `xmlnode_set_namespace'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:270: undefined reference to `jabber_iq_set_callback'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:271: undefined reference to `jabber_iq_send'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:273: undefined reference to `purple_account_get_username'
./build/carbons.o: In function `carbons_plugin_load':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:285: undefined reference to `purple_accounts_get_all_active'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:288: undefined reference to `purple_account_is_connected'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:299: undefined reference to `purple_accounts_get_handle'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:299: undefined reference to `purple_signal_connect'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:300: undefined reference to `purple_plugins_find_with_id'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:300: undefined reference to `purple_signal_connect_priority'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:301: undefined reference to `purple_plugins_find_with_id'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:301: undefined reference to `purple_signal_connect_priority'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:296: undefined reference to `jabber_add_feature'
./build/carbons.o: In function `carbons_enable_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:203: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:201: undefined reference to `purple_debug_error'
./build/carbons.o: In function `carbons_discover_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:245: undefined reference to `purple_debug_info'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:225: undefined reference to `purple_debug_error'
./build/carbons.o: In function `carbons_xml_received_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:121: undefined reference to `purple_debug_warning'
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:133: undefined reference to `purple_debug_error'
./build/carbons.o: In function `carbons_account_connect_cb':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:273: undefined reference to `purple_debug_info'
./build/carbons.o: In function `purple_init_plugin':
/home/masterz/testing/BUILD/carbons-0.2.3/./src/carbons.c:349: undefined reference to `purple_plugin_register'
collect2: error: ld returned 1 exit status
make: *** [Makefile:77: build/carbons.so] Error 1
error: Bad exit status from /home/masterz/testing/BUILDROOT/rpm-tmp.23207 (%build)

**Comment by gkdr** [comment]
hi, thanks for the report!
what distro are you on? it seems to me like you're missing the package with the dev headers. for example, in ubuntu it's `libpurple-dev` and not just `libpurple`.

**Comment by Zombie-Ryushu** [comment]
Mageia. I was able to get it to build  by removing the following from the spec file

export CFLAGS="%{optflags}"
export CPPFLAGS="%{optflags}"
export LDFLAGS="%{ldflags}"

**Comment by Zombie-Ryushu** [comment]
Also, my Spec Did contain:
BuildRequires:  pkgconfig(purple)

**Comment by gkdr** [comment]
glad you got it to work! what "spec file" is that?

**Comment by Zombie-Ryushu** [comment]
Hold on, I'll link you to my hosted copy of the Spec File on ABF
https://abf.rosalinux.ru/zombie/purple-carbons/blob/rosa2016.1/purple-carbons.spec

**Comment by Zombie-Ryushu** [comment]
If you would be interested in repairing other Purple modules, don't keep it a secret.

**Comment by gkdr** [comment]
i'll gladly help if you need assistance with getting my code to work :slightly_smiling_face: since this particular issue seems resolved, i'm closing it.
